
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.3 EDK_O.76xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtft.h"

/*
* The configuration table for devices
*/

XTft_Config XTft_ConfigTable[] =
{
	{
		XPAR_DISPLAY_CNTLR_DEVICE_ID,
		XPAR_DISPLAY_CNTLR_SPLB_BASEADDR,
		XPAR_DISPLAY_CNTLR_DEFAULT_TFT_BASE_ADDR,
		XPAR_DISPLAY_CNTLR_DCR_SPLB_SLAVE_IF,
		XPAR_DISPLAY_CNTLR_DCR_BASEADDR
	}
};


