
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.3 EDK_O.76xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtmrctr.h"

/*
* The configuration table for devices
*/

XTmrCtr_Config XTmrCtr_ConfigTable[] =
{
	{
		XPAR_DUAL_TIMER_COUNTER_DEVICE_ID,
		XPAR_DUAL_TIMER_COUNTER_BASEADDR
	}
};


