
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.3 EDK_O.76xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xsysmon.h"

/*
* The configuration table for devices
*/

XSysMon_Config XSysMon_ConfigTable[] =
{
	{
		XPAR_SYSTEM_MONITOR_DEVICE_ID,
		XPAR_SYSTEM_MONITOR_BASEADDR,
		XPAR_SYSTEM_MONITOR_INCLUDE_INTR
	}
};


