#ifndef CYGONCE_PKGCONF_HAL_MICROBLAZE_GENERIC_H
#define CYGONCE_PKGCONF_HAL_MICROBLAZE_GENERIC_H
/*
 * File <pkgconf/hal_microblaze_generic.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_1
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL 0
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_0
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 9600
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_9600
#define CYGNUM_HAL_RTC_CONSTANTS 1
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 100
#define CYGNUM_HAL_RTC_DENOMINATOR_100
#define CYGNUM_HAL_RTC_PERIOD 1000000
#define CYGNUM_HAL_RTC_PERIOD_1000000
#define CYGHWR_HAL_RTC_USE_AUTO_RESET 1
#define CYGBLD_GLOBAL_OPTIONS 1
#define CYGPKG_HAL_MICROBLAZE_SPARTAN3ESK_OPTIONS 1

#endif
